package com.fx.common.event;

/**
 * {@code EventStatus} — Integer-constant status registry for FX market events.
 *
 * <h2>Why int constants instead of {@code enum}?</h2>
 * <p>
 * Java {@code enum} values are object references. Every comparison via
 * {@code enum.ordinal()} or {@code switch(enum)} requires a virtual dispatch
 * or an array lookup. In the critical path of an HFT pipeline, we need the
 * CPU to execute a single integer comparison instruction (CMP + JE) with no
 * heap access, no class loading overhead, and no risk of auto-boxing.
 *
 * <p>Using {@code static final int} constants:
 * <ul>
 *   <li>Fits in a CPU register — zero memory access required.</li>
 *   <li>Allows the JIT to emit optimal branch-table {@code switch} bytecode.</li>
 *   <li>Is directly storable in the {@link FxMarketEvent} flyweight as a
 *       primitive field — avoiding any object graph pointer chasing.</li>
 * </ul>
 *
 * <h2>Status Lifecycle</h2>
 * <pre>
 *  RECEIVED ──▶ ACCEPTED ──▶ PRICED ──▶ PERSISTED
 *       │            │
 *       └──▶ CREDIT_REJECTED
 *       └──▶ VALIDATION_FAILED
 *       └──▶ PRICING_FAILED
 *       └──▶ ERROR
 * </pre>
 *
 * @author FX Pipeline Team
 * @version 1.0.0
 */
public final class EventStatus {

    // ── Construction prevention ──────────────────────────────────────────────
    // This is a pure constants class; instantiation is meaningless and wasteful.
    private EventStatus() {
        throw new UnsupportedOperationException("EventStatus is a constants utility class");
    }

    // ── Status Constants ─────────────────────────────────────────────────────

    /**
     * Event has been received and decoded by serv-0 (FIX Gateway).
     * This is the initial state set immediately after FIX message parsing.
     */
    public static final int RECEIVED = 0;

    /**
     * Event has passed all risk and credit checks in serv-a.
     * The order is eligible for pricing.
     */
    public static final int ACCEPTED = 1;

    /**
     * Event was rejected by the credit-check engine in serv-a.
     * The client's notional exposure exceeds their credit limit.
     * The event is forwarded to the error queue; no further processing occurs.
     */
    public static final int CREDIT_REJECTED = 2;

    /**
     * Structural FIX message validation failed in serv-0.
     * Missing mandatory tags, malformed price fields, or unsupported message type.
     */
    public static final int VALIDATION_FAILED = 3;

    /**
     * The event has been priced and an execution report generated by serv-b.
     * {@link FxMarketEvent#executedPrice} is now populated with a valid value.
     */
    public static final int PRICED = 4;

    /**
     * Spread application or price computation failed in serv-b.
     * This may occur if the currency pair has no active market data.
     */
    public static final int PRICING_FAILED = 5;

    /**
     * The event has been successfully persisted to the database by serv-c.
     * This is the terminal success state.
     */
    public static final int PERSISTED = 6;

    /**
     * An unrecoverable error occurred in the pipeline.
     * The event is routed to the dedicated error Chronicle Queue for diagnosis.
     * The main processing thread continues without interruption.
     */
    public static final int ERROR = 7;

    // ── Sentinel / Validation Helpers ────────────────────────────────────────

    /**
     * Returns {@code true} if the given status represents a terminal failure.
     *
     * <p>This method uses integer arithmetic rather than collections or string
     * comparison to remain allocation-free and branch-predictor friendly.
     *
     * @param status the {@code EventStatus} integer constant to test
     * @return {@code true} if the event should not proceed further downstream
     */
    public static boolean isTerminalFailure(final int status) {
        // Bitwise approach: failure statuses are odd or above ACCEPTED.
        // Explicit comparison is clearer and equally fast after JIT compilation.
        return status == CREDIT_REJECTED
                || status == VALIDATION_FAILED
                || status == PRICING_FAILED
                || status == ERROR;
    }

    /**
     * Returns a short ASCII label for logging/diagnostics outside the hot path.
     *
     * <p><strong>WARNING:</strong> Do NOT call this method on the critical event
     * loop thread. It creates a {@code String} object. Reserve for error-queue
     * handlers, startup diagnostics, and integration test assertions only.
     *
     * @param status the integer status constant
     * @return a human-readable label string
     */
    public static String toLabel(final int status) {
        return switch (status) {
            case RECEIVED          -> "RECEIVED";
            case ACCEPTED          -> "ACCEPTED";
            case CREDIT_REJECTED   -> "CREDIT_REJECTED";
            case VALIDATION_FAILED -> "VALIDATION_FAILED";
            case PRICED            -> "PRICED";
            case PRICING_FAILED    -> "PRICING_FAILED";
            case PERSISTED         -> "PERSISTED";
            case ERROR             -> "ERROR";
            default                -> "UNKNOWN(" + status + ")";
        };
    }
}
