package com.fx.common.event;

import net.openhft.chronicle.wire.SelfDescribingMarshallable;

/**
 * {@code FxMarketEvent} — Zero-Allocation Flyweight Event DTO.
 *
 * <h2>Flyweight Pattern in HFT Context</h2>
 * <p>
 * In the LMAX Disruptor architecture, a single mutable event object is
 * pre-allocated at startup and reused for every message. This eliminates
 * the GC pressure that would result from allocating millions of new DTOs
 * per second. The flyweight is filled with new values before being written
 * to the Chronicle Queue, and then populated from the queue into a reused
 * instance on the consumer side.
 *
 * <h2>Memory Layout & Cache-Line Alignment</h2>
 * <p>
 * A modern CPU cache line is 64 bytes. We group related primitive fields
 * together so that a single cache-line fetch pulls in all the data an event
 * handler needs in one shot, avoiding expensive cache misses. The fields are
 * ordered by access frequency and logical group:
 * <ol>
 *   <li><b>Identity group</b> ({@code correlationId}, {@code ingressNanoTime})
 *       — needed by every service for correlation and latency measurement.</li>
 *   <li><b>FX instrument group</b> ({@code currencyPair}, {@code side},
 *       {@code notional}) — needed for all business logic.</li>
 *   <li><b>Pricing group</b> ({@code requestedPrice}, {@code executedPrice},
 *       {@code spread}) — written by serv-b, read by serv-c.</li>
 *   <li><b>State group</b> ({@code eventStatus}, {@code clientId}) — status
 *       flag mutated at each pipeline stage.</li>
 * </ol>
 *
 * <h2>No Strings on the Hot Path</h2>
 * <p>
 * Currency pairs (e.g., "EUR/USD") are encoded as a compact {@code long}
 * packing two 3-letter ISO 4217 currency codes into 6 bytes of the long.
 * This avoids {@link String} allocation entirely. The {@link CurrencyPairCodec}
 * inner class provides static encode/decode utilities (decode only used in
 * diagnostics/logging, never on hot path).
 *
 * <h2>Chronicle Wire Integration</h2>
 * <p>
 * Extending {@link SelfDescribingMarshallable} gives Chronicle Wire the ability
 * to serialise/deserialise all fields directly into the memory-mapped
 * Chronicle Queue buffer using {@code BINARY_LIGHT} wire format. No manual
 * read/write methods are required for standard field types.
 *
 * @author FX Pipeline Team
 * @version 1.0.0
 */
public final class FxMarketEvent extends SelfDescribingMarshallable {

    // ─────────────────────────────────────────────────────────────────────────
    // IDENTITY GROUP  (offset 0 in Chronicle Wire binary layout)
    // These two longs occupy the first 16 bytes. On a 64-byte cache line,
    // they arrive with the object header, minimising cache misses for
    // the most universally accessed fields.
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Globally unique, monotonically increasing 64-bit correlation identifier.
     *
     * <p>Generated by {@code CorrelationIdGenerator} in serv-0 using an
     * {@link java.util.concurrent.atomic.AtomicLong}. Sequential longs are
     * vastly superior to UUID strings for the following reasons:
     * <ul>
     *   <li>A {@code long} fits in a single CPU register (8 bytes).</li>
     *   <li>A UUID string is a 36-character heap object (72+ bytes).</li>
     *   <li>Incrementing an {@code AtomicLong} is a single CAS CPU instruction.</li>
     *   <li>Sequential IDs have perfect cache-locality when stored in arrays.</li>
     * </ul>
     */
    public long correlationId;

    /**
     * High-resolution UTC nanosecond timestamp captured at the moment the
     * FIX message byte buffer was first read in serv-0.
     *
     * <p>{@link System#nanoTime()} provides monotonic nanosecond resolution.
     * It does not allocate. Stored as a raw {@code long} — never converted
     * to a {@link java.time.Instant} on the hot path (Instant allocates).
     */
    public long ingressNanoTime;

    // ─────────────────────────────────────────────────────────────────────────
    // FX INSTRUMENT GROUP  (offset 16)
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Encoded currency pair identifier.
     *
     * <p>ISO 4217 currency codes are 3 ASCII characters each (A-Z, value 65–90).
     * Both codes of a pair fit in 6 bytes. We pack them into a single {@code long}:
     * <pre>
     *   Bits 47–24: base currency  (e.g., 'E','U','R' for EUR)
     *   Bits 23–0:  quote currency (e.g., 'U','S','D' for USD)
     *   Bits 63–48: reserved / zero
     * </pre>
     * Use {@link CurrencyPairCodec#encode(byte[], byte[])} to populate this field.
     */
    public long currencyPairCode;

    /**
     * Trade side: {@code 1} = BUY, {@code -1} = SELL.
     *
     * <p>A signed byte keeps the footprint minimal. The JIT will widen to int
     * for arithmetic, but the storage remains 1 byte in the Chronicle buffer.
     */
    public byte side;

    /**
     * Order notional amount in the base currency's minor units (e.g., USD cents).
     *
     * <p>Using {@code long} minor units instead of {@code double} eliminates
     * floating-point rounding errors inherent in IEEE 754 double arithmetic —
     * critical for financial calculations where even a single cent error can
     * trigger regulatory issues.
     *
     * <p>Example: USD 1,000,000.00 is stored as {@code 100_000_000L} (cents).
     */
    public long notionalMinorUnits;

    /**
     * Client tier code used by the credit-check engine in serv-a.
     * Higher values indicate more privileged/larger-limit clients.
     * {@code 0} = unknown / uninitialised.
     */
    public int clientTier;

    // ─────────────────────────────────────────────────────────────────────────
    // PRICING GROUP  (offset ~40)
    // Written by serv-b; read-only in serv-c.
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Client's requested execution price, encoded as minor units (e.g., pips × 10^5).
     *
     * <p>Stored as a {@code long} scaled integer. For EUR/USD, 1 pip = 0.0001,
     * so the price 1.0850 is stored as {@code 108500L} (price × 100,000).
     * This scale avoids all floating-point imprecision on the hot path.
     */
    public long requestedPriceScaled;

    /**
     * Final executed price assigned by the pricing engine in serv-b.
     * Uses the same scaling convention as {@link #requestedPriceScaled}.
     * Initialised to {@code 0L}; a value of {@code 0L} means "not yet priced".
     */
    public long executedPriceScaled;

    /**
     * Spread in minor units applied by the pricing engine (bid-ask difference).
     * Always non-negative. A value of {@code 0L} indicates no spread (e.g., error path).
     */
    public long spreadScaled;

    // ─────────────────────────────────────────────────────────────────────────
    // STATE GROUP  (offset ~64+)
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Current processing status of this event.
     * Must be one of the {@link EventStatus} integer constants.
     * Mutated in-place at each pipeline stage without creating new objects.
     */
    public int eventStatus;

    /**
     * 64-bit internal client identifier.
     *
     * <p>Pre-mapped from FIX tag 49 (SenderCompID) at ingress in serv-0.
     * Stored as a {@code long} to avoid String allocation. The mapping table
     * (clientId ↔ SenderCompID) is a pre-loaded off-heap hash map.
     */
    public long clientId;

    /**
     * FIX message type tag value (e.g., {@code 'D'} = New Order Single).
     * Stored as a single byte; no String conversion required.
     */
    public byte fixMsgType;

    /**
     * Sequence number from the FIX session layer (FIX tag 34).
     * Used for gap-fill detection and replay ordering.
     */
    public long fixSeqNum;

    // ─────────────────────────────────────────────────────────────────────────
    // FLYWEIGHT LIFECYCLE METHODS
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Resets all fields to their zero/sentinel values, preparing this flyweight
     * instance for reuse with the next event.
     *
     * <p><b>LMAX principle:</b> Resetting a pre-allocated object and filling it
     * with new data is orders of magnitude faster than allocating a new object,
     * because it avoids triggering the GC write barrier and keeps the object
     * in the CPU's L1/L2 cache across consecutive uses.
     *
     * <p>This method must be called by the event loop before populating the
     * flyweight from a queue excerpt or a decoded FIX message.
     */
    public void reset() {
        correlationId        = 0L;
        ingressNanoTime      = 0L;
        currencyPairCode     = 0L;
        side                 = 0;
        notionalMinorUnits   = 0L;
        clientTier           = 0;
        requestedPriceScaled = 0L;
        executedPriceScaled  = 0L;
        spreadScaled         = 0L;
        eventStatus          = EventStatus.RECEIVED;
        clientId             = 0L;
        fixMsgType           = 0;
        fixSeqNum            = 0L;
    }

    /**
     * Copies all fields from {@code source} into this instance.
     *
     * <p>Used by error-routing and diagnostic paths where an event must be
     * forwarded to the error queue while the main flyweight continues processing.
     * All field copies are primitive assignments — zero allocations.
     *
     * @param source the event to copy fields from; must not be {@code null}
     */
    public void copyFrom(final FxMarketEvent source) {
        // Defensive programming: if source were somehow null, we'd get an NPE here.
        // However, by design, flyweight instances are never null in this pipeline
        // (they are pre-allocated at service startup). This method is not on the
        // hot path, so the cost of a reference read is acceptable.
        this.correlationId        = source.correlationId;
        this.ingressNanoTime      = source.ingressNanoTime;
        this.currencyPairCode     = source.currencyPairCode;
        this.side                 = source.side;
        this.notionalMinorUnits   = source.notionalMinorUnits;
        this.clientTier           = source.clientTier;
        this.requestedPriceScaled = source.requestedPriceScaled;
        this.executedPriceScaled  = source.executedPriceScaled;
        this.spreadScaled         = source.spreadScaled;
        this.eventStatus          = source.eventStatus;
        this.clientId             = source.clientId;
        this.fixMsgType           = source.fixMsgType;
        this.fixSeqNum            = source.fixSeqNum;
    }

    // ─────────────────────────────────────────────────────────────────────────
    // NESTED CODEC UTILITY
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * {@code CurrencyPairCodec} — Encodes/decodes ISO 4217 currency pair codes
     * as a single {@code long} without any {@link String} allocation.
     *
     * <h2>Encoding Scheme</h2>
     * <p>
     * Each ASCII character of a currency code occupies 8 bits. We pack the
     * 6 characters of a pair (3 base + 3 quote) into the low 48 bits of a
     * {@code long}:
     * <pre>
     *   [byte5][byte4][byte3] = base  currency (e.g., E=0x45, U=0x55, R=0x52)
     *   [byte2][byte1][byte0] = quote currency (e.g., U=0x55, S=0x53, D=0x44)
     * </pre>
     * Example: EUR/USD → {@code 0x000045555255534400L} (conceptually 6 bytes).
     */
    public static final class CurrencyPairCodec {

        /** Expected byte-length of each ISO 4217 currency code (always 3). */
        private static final int CURRENCY_CODE_LENGTH = 3;

        /** Number of bits per byte used in the bit-packing scheme. */
        private static final int BITS_PER_BYTE = 8;

        private CurrencyPairCodec() {
            throw new UnsupportedOperationException("Utility class");
        }

        /**
         * Encodes two 3-byte ASCII currency codes into a single {@code long}.
         *
         * <p>This method operates entirely on primitive arrays — zero object
         * allocations. The caller is expected to provide pre-allocated byte
         * buffers that are filled from the FIX message parser.
         *
         * @param baseCurrency  3-byte ASCII currency code (e.g., 'E','U','R')
         * @param quoteCurrency 3-byte ASCII currency code (e.g., 'U','S','D')
         * @return packed {@code long} representation of the currency pair
         * @throws IllegalArgumentException if either array is not exactly 3 bytes
         */
        public static long encode(final byte[] baseCurrency, final byte[] quoteCurrency) {
            if (baseCurrency.length != CURRENCY_CODE_LENGTH
                    || quoteCurrency.length != CURRENCY_CODE_LENGTH) {
                // This exception is only thrown on invalid FIX messages — i.e., the
                // error path, not the hot path. String construction here is acceptable.
                throw new IllegalArgumentException(
                        "Currency codes must be exactly 3 bytes each");
            }
            long encoded = 0L;
            // Pack base currency into bits 40–16 (3 bytes, high side)
            for (int i = 0; i < CURRENCY_CODE_LENGTH; i++) {
                encoded |= ((long) (baseCurrency[i] & 0xFF))
                        << ((5 - i) * BITS_PER_BYTE);
            }
            // Pack quote currency into bits 23–0 (3 bytes, low side)
            for (int i = 0; i < CURRENCY_CODE_LENGTH; i++) {
                encoded |= ((long) (quoteCurrency[i] & 0xFF))
                        << ((2 - i) * BITS_PER_BYTE);
            }
            return encoded;
        }

        /**
         * Decodes a packed {@code long} currency pair code back into a human-readable
         * string for diagnostic/logging purposes.
         *
         * <p><b>WARNING:</b> This method allocates a {@link String}. Call it ONLY
         * from diagnostic, logging, or test code — never from the hot path.
         *
         * @param code the packed {@code long} produced by {@link #encode}
         * @return a human-readable string such as {@code "EUR/USD"}
         */
        public static String decode(final long code) {
            final byte[] base  = new byte[CURRENCY_CODE_LENGTH];
            final byte[] quote = new byte[CURRENCY_CODE_LENGTH];
            for (int i = 0; i < CURRENCY_CODE_LENGTH; i++) {
                base[i]  = (byte) ((code >> ((5 - i) * BITS_PER_BYTE)) & 0xFF);
                quote[i] = (byte) ((code >> ((2 - i) * BITS_PER_BYTE)) & 0xFF);
            }
            return new String(base) + "/" + new String(quote);
        }
    }
}
